version: '3'
services:
  proxy:
    container_name: proxy
    # build: ./proxy
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./proxy/proxy.conf:/etc/nginx/conf.d/default.conf
    links:
      - server1
      - server2

  server1:
    container_name: server1
    # build: ./server1
    image: nginx
    expose:
      - 80
    volumes:
      - ./server1/index.html:/usr/share/nginx/html/index.html

  server2:
    container_name: server2
    # build: ./server2
    image: nginx
    expose:
      - 80
    volumes:
      - ./server2/index.html:/usr/share/nginx/html/index.html